
from app.models.schemas import BillingData


MOCK_BILLING_DATA: dict[str, BillingData] = {
    "cust_001": BillingData(
        customer_id="cust_001",
        plan_name="Unlimited Plus",
        monthly_plan_cost=65.0,
        previous_total=71.2,
        current_total=126.7,
        activation_fee=35.0,
        prorated_charge=12.0,
        overage_charge=8.5,
        taxes_and_fees=6.2,
        primary_increase_reason="Your bill increased mainly because this cycle includes a one-time activation fee, a partial-month prorated charge, and a small data overage.",
        detailed_reasons=[
            "A one-time $35.00 activation fee was added for the recent line or service change.",
            "A $12.00 prorated charge was added because the plan change started in the middle of the billing cycle.",
            "A $8.50 overage charge was added after usage went beyond the included limit.",
        ],
        recommended_next_step="The activation fee is one-time, so the next bill should be lower if usage stays within plan limits.",
        is_one_time_charge=True,
    ),
    "cust_002": BillingData(
        customer_id="cust_002",
        plan_name="5G Start",
        monthly_plan_cost=55.0,
        previous_total=58.4,
        current_total=64.1,
        activation_fee=0.0,
        prorated_charge=0.0,
        overage_charge=0.0,
        taxes_and_fees=9.1,
        primary_increase_reason="Your bill is mostly stable, and the small increase comes from routine taxes and fees rather than a major account change.",
        detailed_reasons=[
            "Your base plan charge stayed the same this month.",
            "There were no activation, prorated, or overage charges added this cycle.",
            "Most of the difference comes from normal taxes and fees.",
        ],
        recommended_next_step="No action is needed unless you want a line-by-line review of taxes and fees.",
        is_one_time_charge=False,
    ),
    "cust_003": BillingData(
        customer_id="cust_003",
        plan_name="Unlimited Welcome",
        monthly_plan_cost=50.0,
        previous_total=52.6,
        current_total=88.6,
        activation_fee=0.0,
        prorated_charge=18.0,
        overage_charge=12.0,
        taxes_and_fees=8.6,
        primary_increase_reason="Your bill went up because of a mid-cycle plan adjustment that created a prorated charge, plus an added overage charge.",
        detailed_reasons=[
            "A $18.00 prorated charge was added because service changes took effect in the middle of the billing cycle.",
            "A $12.00 overage charge was added for usage beyond the included allowance.",
            "Taxes and fees increased along with the higher total.",
        ],
        recommended_next_step="If you expect similar usage, reviewing your current plan could help reduce future overages.",
        is_one_time_charge=False,
    ),
    "cust_004": BillingData(
        customer_id="cust_004",
        plan_name="Unlimited Ultimate",
        monthly_plan_cost=80.0,
        previous_total=83.9,
        current_total=84.7,
        activation_fee=0.0,
        prorated_charge=0.0,
        overage_charge=0.0,
        taxes_and_fees=4.7,
        primary_increase_reason="There is no meaningful bill spike here; the total changed only slightly because of normal monthly taxes and fees.",
        detailed_reasons=[
            "Your plan charge stayed steady this month.",
            "There were no one-time fees or overage charges added.",
            "The small difference is driven by standard taxes and fees.",
        ],
        recommended_next_step="This looks like a normal bill, so no action is needed unless you want a detailed line-by-line review.",
        is_one_time_charge=False,
    ),
    "cust_005": BillingData(
        customer_id="cust_005",
        plan_name="Unlimited Plus",
        monthly_plan_cost=65.0,
        previous_total=67.3,
        current_total=109.8,
        activation_fee=0.0,
        prorated_charge=22.5,
        overage_charge=14.0,
        taxes_and_fees=8.3,
        primary_increase_reason="Your bill increased because of a mid-cycle prorated charge and a usage overage, rather than a permanent jump in the base plan price.",
        detailed_reasons=[
            "A $22.50 prorated charge was added because your service or plan changed partway through the cycle.",
            "A $14.00 overage charge was added after usage went over the included amount.",
            "Your base monthly plan price itself did not drive most of the increase.",
        ],
        recommended_next_step="If the plan change is complete and usage stays lower next month, your bill should come down from this level.",
        is_one_time_charge=False,
    ),
    "cust_006": BillingData(
        customer_id="cust_006",
        plan_name="5G Start",
        monthly_plan_cost=55.0,
        previous_total=60.2,
        current_total=142.9,
        activation_fee=35.0,
        prorated_charge=24.0,
        overage_charge=19.5,
        taxes_and_fees=9.4,
        primary_increase_reason="Your bill is much higher this cycle because several extra charges landed at once: a one-time activation fee, a prorated service charge, and a data overage.",
        detailed_reasons=[
            "A one-time $35.00 activation fee was added this cycle.",
            "A $24.00 prorated charge was added because service changes started mid-cycle.",
            "A $19.50 overage charge was added after usage exceeded the included limit.",
        ],
        recommended_next_step="The activation fee should not repeat, but reviewing the recent service change and data usage would help prevent another high bill.",
        is_one_time_charge=True,
    ),
}


def get_billing_data(customer_id: str) -> BillingData:
    return MOCK_BILLING_DATA.get(
        customer_id,
        BillingData(
            customer_id=customer_id,
            plan_name="Unlimited Plus",
            monthly_plan_cost=65.0,
            previous_total=72.1,
            current_total=84.3,
            activation_fee=0.0,
            prorated_charge=0.0,
            overage_charge=6.0,
            taxes_and_fees=13.3,
            primary_increase_reason="Your bill is slightly higher mainly because of a small overage and normal taxes and fees.",
            detailed_reasons=[
                "Your base plan stayed about the same this month.",
                "A small overage charge was added after usage passed the included amount.",
                "The remaining difference comes from standard taxes and fees.",
            ],
            recommended_next_step="If usage stays within plan limits next month, the total should be closer to your usual amount.",
            is_one_time_charge=False,
        ),
    )
